# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 2eb5804a745c60cdb7f3e509469110689f150402

{
  "title": "Шкаф IKEA",
  "description": "Срочно",

  "title": "Диван IKEA",
  "description": "Срочно"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/3/
Content-Type: application/json
Authorization: Token 2eb5804a745c60cdb7f3e509469110689f150402

{
  "status": "CLOSED"
}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=1
Content-Type: application/json


###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2023-12-04
Content-Type: application/json

###

GET {{baseUrl}}/favorite/?person
Content-Type: application/json

###

